const ASSISTANCE = {
  push: {
    type: "push",
    exercises: {
      push78965: "dip",
      push12345: "push-up",
      push59876: "dumbbell bench press",
      push78451: "dumbbell incline press",
    },
    reps: "50-100 reps",
  },
  pull: {
    type: "pull",
    exercises: {
      pull78965: "pull-up",
      pull12345: "row",
      pull59876: "lat pulldown",
      pull78451: "inverted row",
      pull54321: "curl",
      pull54123: "shrug",
    },
    reps: "50-100 reps",
  },
  accessory: {
    type: "accessory",
    exercises: {
      accs78965: "any abdominal exercise",
      accs12345: "back raise",
      accs59876: "reverse hyperextension",
      accs78451: "lunge",
      accs54321: "step-up",
      accs54123: "split squat",
      accs65789: "one-let squat",
      accs73195: "kettlebell swing",
      accs79136: "kettlebell snatch",
    },
    reps: "50-100 reps",
  },
  conditioning: {
    type: "conditioning",
    exercises: {
      cond78965: "prowler",
      cond12345: "sled",
    },
    reps: "20-30 mins",
  },
};

const PROGRAM = {
  name: "5/3/1 for Hardgainers",
  source:
    "https://www.jimwendler.com/blogs/jimwendler-com/5-3-1-for-hardgainers",
  weeks: [
    {
      week: 1,
      days: [
        {
          day: "Day A",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 85,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day B",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 85,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
        {
          day: "Day D",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 85,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day E",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
      ],
    },
    {
      week: 2,
      days: [
        {
          day: "Day A",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 90,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day B",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 90,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
        {
          day: "Day D",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 90,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day E",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 90,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
      ],
    },
    {
      week: 3,
      days: [
        {
          day: "Day A",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 95,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day B",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 95,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
        {
          day: "Day D",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 95,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [ASSISTANCE.push, ASSISTANCE.pull, ASSISTANCE.accessory],
        },
        {
          day: "Day E",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 95,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            ASSISTANCE.push,
            ASSISTANCE.pull,
            ASSISTANCE.conditioning,
          ],
        },
      ],
    },
  ],
  notes: [
    "Training Max (TM): The Training Max will remain constant. The TM for each lift will begin at 85% of your 1RM or estimated 1RM. Every percentage listed in the program is based on your TM, not your actual max.",
    "Standard 5/3/1 rules apply: Your TM increases 5 or 10 pounds after each cycle.",
    "If you can't hit at least 5 reps at 95%, you have the wrong TM. Adjust accordingly.",
    "Assistance work is essential but should not be trained like your squat or deadlift.",
    "Recovery is as important as training. Be proactive on your off days.",
  ],
};
