const PROGRAM = {
  name: "5/3/1 for Hardgainers",
  source:
    "https://www.jimwendler.com/blogs/jimwendler-com/5-3-1-for-hardgainers",
  weeks: [
    {
      week: 1,
      days: [
        {
          day: "Monday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 85,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Tuesday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 85,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
        {
          day: "Thursday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 85,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Friday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 65,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 65,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
      ],
    },
    {
      week: 2,
      days: [
        {
          day: "Monday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 90,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Tuesday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 90,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
        {
          day: "Thursday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 90,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Friday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 70,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 80,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 90,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 70,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
      ],
    },
    {
      week: 3,
      days: [
        {
          day: "Monday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Squat",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 95,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "20",
              sets: 1,
              notes: "Widowmaker set",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Tuesday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Bench Press",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 95,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
        {
          day: "Thursday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Deadlift",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "top_set",
              percent_tm: 95,
              reps: "5+",
              sets: 1,
              notes: "PR set",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "5",
              sets: 5,
              notes: "5 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Accessory: abs/low back/single-leg/KB swing/KB snatch (choose one) - 50-100 total reps",
          ],
        },
        {
          day: "Friday",
          warm_up: ["Agile 8", "Box Jump x 10 total reps"],
          main_lift: "Press (Overhead Press)",
          sets: [
            {
              type: "warmup",
              percent_tm: 75,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "warmup",
              percent_tm: 85,
              reps: "5",
              sets: 1,
              notes: "",
            },
            {
              type: "work",
              percent_tm: 95,
              reps: "5",
              sets: 1,
              notes: "No extra reps",
            },
            {
              type: "backoff",
              percent_tm: 75,
              reps: "5",
              sets: 10,
              notes: "10 sets of 5",
            },
          ],
          assistance: [
            "Push: Dip, push-up, or DB bench/incline/press (choose one) - 50-100 total reps",
            "Pull: Pull-up, row, lat pulldown, inverted row, curl, shrug (choose one) - 50-100 total reps",
            "Conditioning: Prowler or Sled - 20-30 minutes",
          ],
        },
      ],
    },
  ],
  notes: [
    "Training Max (TM): The Training Max will remain constant. The TM for each lift will begin at 85% of your 1RM or estimated 1RM. Every percentage listed in the program is based on your TM, not your actual max.",
    "Standard 5/3/1 rules apply: Your TM increases 5 or 10 pounds after each cycle.",
    "If you can't hit at least 5 reps at 95%, you have the wrong TM. Adjust accordingly.",
    "Assistance work is essential but should not be trained like your squat or deadlift.",
    "Recovery is as important as training. Be proactive on your off days.",
  ],
};
